import abstract_axiomatic_homotopy_theory_algebraic_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace abstract_axiomatic_homotopy_theory_algebraic_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end abstract_axiomatic_homotopy_theory_algebraic_lemma_canonical_lane_mathlib
end HautevilleHouse
